# Generated by Django 4.2.2 on 2023-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='read_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='languages',
            name='speak_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='languages',
            name='write_status',
            field=models.BooleanField(default=0),
        ),
    ]
